# This file was generated by GoReleaser. DO NOT EDIT.
# Maintainer: Bartek Pacia <barpac02@gmail.com>

pkgname='fhome-bin'
pkgver=0.1.15
pkgrel=1
pkgdesc='Interact with smart home devices connected to F&Home'
url='https://github.com/bartekpacia/fhome'
arch=('aarch64' 'x86_64')
license=('')
provides=('fhome')
conflicts=('fhome')

source_aarch64=("${pkgname}_${pkgver}_aarch64.tar.gz::https://github.com/bartekpacia/fhome/releases/download/v0.1.15/fhome_0.1.15_linux_arm64.tar.gz")
sha256sums_aarch64=('aec25f80258aba6d43d640b69a6b397036375b85ef54ce7e2c1d37767f258e8d')

source_x86_64=("${pkgname}_${pkgver}_x86_64.tar.gz::https://github.com/bartekpacia/fhome/releases/download/v0.1.15/fhome_0.1.15_linux_amd64.tar.gz")
sha256sums_x86_64=('c116d7a491a5026f07d0e48b09d9a16d2c1e6ea30e01cba71faec5c2398f0853')

package() {
  cd "$pkgname-$pkgver"
  # bin
  install -Dm755 fhome "${pkgdir}/usr/bin/fhome"

  # license
  install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/mybin/LICENSE"

  # completions
  mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
  mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
  install -Dm755 autocomplete/bash_autocomplete_fhome "${pkgdir}/usr/share/bash-completion/completions/fhome"
  install -Dm755 autocomplete/zsh_autocomplete_fhome "${pkgdir}/usr/share/zsh/site-functions/_fhome"

  # man pages
  # install -Dm644 "./manpages/mybin.1.gz" "${pkgdir}/usr/share/man/man1/mybin.1.gz"
}
